spring:
  data:
    mongodb:
      uri: mongodb+srv://gurkancakir:Gurkan34@cluster0.ijo4e.mongodb.net/shortlink?retryWrites=true&w=majority

  server:
    port: ${PORT:8080}

# Graphql
graphql:
  servlet:
    mapping: /api/v1/graphql
  playground:
    enabled: true
    endpoint: /api/v1/graphql